#!/usr/bin/env ansible-playbook
---
- name: Install dotfiles
  hosts: localhost
  roles:
    - dotfiles
  vars:
    git_name: Ronald Weber
    git_email: ronaldxweber@gmail.com
    git_aliases:
      ap: add -p
      ci: commit
      cia: commit --amend
      ds: diff --staged
      l: log
      pu: push
      st: status
    zsh_aliases:
      g: git
      gl: git log --oneline
      py: ipython

- name: Enable ssh-agent
  hosts: devpcs
  roles:
    - ssh-agent
  vars:
    ssh_agent_key_timeout: 3600
