#!/usr/bin/env ansible-playbook
---
- name: Install dotfiles
  hosts: devpcs
  roles:
    - dotfiles
  vars:
    git_name: Ronald Weber
    git_email: ronaldxweber@gmail.com
    git_aliases:
      ap: add -p
      b: branch
      ci: commit
      cia: commit --amend
      cim: commit -m
      co: checkout
      cob: checkout -b
      di: diff
      ds: diff --staged
      f: fetch --all --tags
      l: log
      lp: log -p
      pu: push
      pl: pull
      rbi: rebase --interactive
      st: status
      t: tag
    zsh_aliases:
      c: clear
      g: git
      gl: git log --oneline
      gk: gitk --all&
      mhz: watch -n 1 "grep MHz /proc/cpuinfo"
      py: ipython
      v: nvim
      zzz: systemctl suspend

- name: Enable ssh-agent
  hosts: devpcs
  roles:
    - ssh-agent
  vars:
    ssh_agent_key_timeout: 3600
