set-option -g default-shell /bin/zsh
set-option -g history-limit 50000
setw -g mouse on

### titles
set -g set-titles on
set -g set-titles-string "#S:#I:#W - \"#T\" #{session_alerts}"

### status
set -g status on
set -g status-bg colour0
set -g status-fg default
set -g status-interval 15
set -g status-justify left
set -g status-keys vi
set -g status-left "#[fg=colour187,bg=colour242,bold] #S #[fg=colour242,bg=colour0,nobold,nounderscore,noitalics]"
set -g status-left-length 100
set -g status-position bottom
set -g status-right "#[fg=colour242,bg=colour0,nobold,nounderscore,noitalics]#[fg=colour187,bg=colour242] %Y-%m-%d  %H:%M #[fg=colour9,bg=colour242]#[fg=colour187,bg=colour9] #h "
set -g status-right-length 100

### windows
set -g window-status-format "#[fg=colour0,bg=colour10,nobold,noitalics,nounderscore] #[fg=colour187]#I  #W #F #[fg=colour10,bg=colour0]"
set -g window-status-current-format "#[fg=colour0,bg=colour23,nobold,noitalics,nounderscore] #[fg=colour187]#I  #W #F #[fg=colour23,bg=colour0]"
set -g window-status-separator ""
