#SPDX-License-Identifier: MIT
---
# tasks file for ssh-agent

- name: directory for ssh-agent user unit file is present
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: ssh-agent user unit file is present
  ansible.builtin.template:
    src: "ssh-agent.service.j2"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/ssh-agent.service"

- name: set SSH_AUTH_SOCK in shells
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    regexp: '^export SSH_AUTH_SOCK='
    line: 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"'
    create: true
    mode: '0644'

- name: ssh-agent user service is running
  ansible.builtin.systemd_service:
    name: ssh-agent.service
    state: started
    enabled: true
    scope: user
